// Generated by gencpp from file glider_msg/cobamsg.msg
// DO NOT EDIT!


#ifndef GLIDER_MSG_MESSAGE_COBAMSG_H
#define GLIDER_MSG_MESSAGE_COBAMSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace glider_msg
{
template <class ContainerAllocator>
struct cobamsg_
{
  typedef cobamsg_<ContainerAllocator> Type;

  cobamsg_()
    : a(0)
    , b(0)
    , c(0.0)
    , kata()  {
    }
  cobamsg_(const ContainerAllocator& _alloc)
    : a(0)
    , b(0)
    , c(0.0)
    , kata(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _a_type;
  _a_type a;

   typedef int32_t _b_type;
  _b_type b;

   typedef float _c_type;
  _c_type c;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _kata_type;
  _kata_type kata;





  typedef boost::shared_ptr< ::glider_msg::cobamsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::glider_msg::cobamsg_<ContainerAllocator> const> ConstPtr;

}; // struct cobamsg_

typedef ::glider_msg::cobamsg_<std::allocator<void> > cobamsg;

typedef boost::shared_ptr< ::glider_msg::cobamsg > cobamsgPtr;
typedef boost::shared_ptr< ::glider_msg::cobamsg const> cobamsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::glider_msg::cobamsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::glider_msg::cobamsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::glider_msg::cobamsg_<ContainerAllocator1> & lhs, const ::glider_msg::cobamsg_<ContainerAllocator2> & rhs)
{
  return lhs.a == rhs.a &&
    lhs.b == rhs.b &&
    lhs.c == rhs.c &&
    lhs.kata == rhs.kata;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::glider_msg::cobamsg_<ContainerAllocator1> & lhs, const ::glider_msg::cobamsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace glider_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::glider_msg::cobamsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::glider_msg::cobamsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::glider_msg::cobamsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::glider_msg::cobamsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::glider_msg::cobamsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::glider_msg::cobamsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::glider_msg::cobamsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a436b8d370a26d189e735c968518dc40";
  }

  static const char* value(const ::glider_msg::cobamsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa436b8d370a26d18ULL;
  static const uint64_t static_value2 = 0x9e735c968518dc40ULL;
};

template<class ContainerAllocator>
struct DataType< ::glider_msg::cobamsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "glider_msg/cobamsg";
  }

  static const char* value(const ::glider_msg::cobamsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::glider_msg::cobamsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 a\n"
"int32 b\n"
"float32 c\n"
"string kata\n"
;
  }

  static const char* value(const ::glider_msg::cobamsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::glider_msg::cobamsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.kata);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cobamsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::glider_msg::cobamsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::glider_msg::cobamsg_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<int32_t>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<int32_t>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<float>::stream(s, indent + "  ", v.c);
    s << indent << "kata: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.kata);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GLIDER_MSG_MESSAGE_COBAMSG_H
